Md feature/5/search by tag
NSS-Day-Cohort-69/tabloid-one-more-div pull request #72
Opened 2024-06-05 21:25 UTC by Michael-Deitz

### **Purpose**
To allow a user to filter what post they see by tag

### **Files Changed**
- Added UseState to set the tags, and tagId in `PostList.jsx`
- Added a useEffect to get all the tags in `PostList.jsx`
- Added a filter to filter the post if a tag is selected in `PostList.jsx`
- Added the input field with the tags mapped in the options in `PostList.jsx`
- Added the corresponding tags to their post in `PostList.jsx` 

### **To Test**

Fetch, setup, and run according to project README, then confirm the following

- Logged in user can see the tags on a post
- Logged in user can click the dropdown and select a tag
- Logged in user gets an updated view of the corresponding post with the selected tag

2024-06-05 21:47 UTC, ztrouy requested changes

2024-06-05 21:47 UTC, ztrouy commented on client/src/components/posts/PostList.jsx
> +    }, [posts, categoryId, tagId])
I would add categories and tags to this dependency array

2024-06-05 21:47 UTC, ztrouy commented on client/src/components/posts/PostList.jsx
> +                        {p.tags.length > 0 && (
Please indent 114 once, and 115-122 twice

2024-06-06 14:11 UTC, joshuahamrick approved these changes

2024-06-06 15:34 UTC, ztrouy approved these changes
:shipit:

2024-06-06 15:34 UTC, merged