Cc feature/21/reactivate a user
NSS-Day-Cohort-69/tabloid-one-more-div pull request #83
Opened 2024-06-06 20:18 UTC by ccote95

### Purpose
To implement the ability to reactivate a user

### Files Changed 
- Rendered the deactivated users in `ReactivateUser.jsx`
- Added the route for viewing deactivated users in `ApplicationViews.jsx`
- Added navigation functionality to the view deactivated user profiles view `UserProfilesList.jsx`

### Testing
Fetch, setup, and run according to the project README. but do not create a new migrations
Confirm the following:
- As an Admin when viewing the user profile, click on the view deactivated button
- When you do, you will be navigated to the reactivate user view, and only deactivated users will be rendered
- After you click reactivate, that user profile will be activated and will no longer be rendered.

closes #21

2024-06-06 20:18 UTC, joshuahamrick approved these changes
🚀

2024-06-06 20:35 UTC, Michael-Deitz approved these changes

2024-06-06 21:41 UTC, ztrouy requested changes

2024-06-06 21:41 UTC, ztrouy commented on client/src/components/ApplicationViews.jsx
> +          path=":id/reactivate"
Change path to `path="reactivate"`, and indent lines 49-55

2024-06-06 21:41 UTC, ztrouy commented on client/src/components/userprofiles/UserProfilesList.jsx
> +        <Button onClick={() => {navigate("userprofile/reactivate")}}>View Deactivated</Button>
Change navigate to `navigate("reactivate")`

2024-06-06 21:41 UTC, ztrouy commented on client/src/components/userprofiles/UserProfilesList.jsx
Remove whitespace line

2024-06-06 21:41 UTC, ztrouy commented on client/src/components/userprofiles/UserProfilesList.jsx
>    };
Add a newline between the closing tag parenthesis of `getUserProfiles()` and the useEffect below it

2024-06-06 21:41 UTC, ztrouy commented on client/src/components/userprofiles/UserProfilesList.jsx
>  import { Button, ButtonToolbar, Card, CardBody, CardTitle } from "reactstrap";
Remove unused import "ButtonToolbar"

2024-06-06 21:41 UTC, ztrouy commented on client/src/components/userprofiles/ReactivateUser.jsx
> +    };
Add a line of whitespace between `getUserProfiles()` and the useEffect below it

2024-06-06 21:41 UTC, ztrouy commented on client/src/components/userprofiles/ReactivateUser.jsx
> +{  const [userprofiles, setUserProfiles] = useState([]);
Move state onto a new line, rather than being on the same line as the opening curly bracket

2024-06-07 14:53 UTC, ztrouy approved these changes
:shipit:

2024-06-07 14:54 UTC, merged